### ISSUE TITLE
Error finishing downloading 

### ISSUE THREAD

**Issue by Mindtester123** [FlinTyX/Animalia#12]
I press download and wait after it said this 
![Screenshot_20230213-192437](https://user-images.githubusercontent.com/125267865/218445319-c6b134ef-8b27-4cf1-bee4-5219c93679a2.jpg)

**Comment by FlinTyX** [comment]
Sorry for the error @Mindtester123 , this may probably be an import error, or an OS issue. I will check if the mod browser is struggling to download the `.jar` properly
If you mind, try downloading the mod directly from https://github.com/FlinTyX/Animalia/releases/tag/v1.0-java
