### ISSUE TITLE
[suggestion] phrog

### ISSUE THREAD

**Issue by USMP-lancer** [FlinTyX/Animalia#4]
created by placing a birdbath looking structure and putting a frog into it, creating a phrog turret that shoots bubbles rapidly, though not for a larg amount of range

**Comment by USMP-lancer** [comment]
phrog because funny spelling

**Comment by FlinTyX** [comment]
im actually working on a "base" for animals
it's very WIP and im not working on it for now, just an idea.

![image](https://user-images.githubusercontent.com/69006175/159759778-fb978919-7d8d-4409-95ce-3ff5cf0f3654.png)
