### ISSUE TITLE
Frogs teleporting me to another place

### ISSUE THREAD

**Issue by LightningEngine** [FlinTyX/Animalia#5]
When the frog is born and put in a water tile by the payload conveyor the camera gets teleported to the middle of the map
I am using a mobile

https://user-images.githubusercontent.com/95182115/160615888-a07d00d5-3153-4d02-aefc-c87f8a8a4f40.mp4

**Comment by FlinTyX** [comment]
Thanks for reporting.
It's fixed in the dev branch, I'll be releasing it as soon as I can finish all the new content.
