### ISSUE TITLE
Yet another crash issue

### ISSUE THREAD

**Issue by Fabizocker456** [FlinTyX/Animalia#6]
I'm in mobile, latest build (135.2)
Crash occurs upon opening the core DB entry about the exotic frog. All other frog entries seem to work. It also occurs without any (other) mods.

> EcmaError: 'TypeError: Cannot find function statValue in object [object global]. (ANIui#43)'
ScriptRuntime.constructError: 3741
ScriptRuntime.constructError: 3721
ScriptRuntime.typeError: 3750
ScriptRuntime.typeError2: 3766
ScriptRuntime.notFunctionError: 3829
ScriptRuntime.getPropFunctionAndThisHelper: 2192
ScriptRuntime.getPropFunctionAndThis: 2175
ANIui_7._c_anonymous_7: 43
ANIui_7.call: 77
OptRuntime.callName: 51
ANIunitTypes_27._c_anonymous_2: 57
ANIunitTypes_27.call: 47
ContextFactory.doTopCall: 328
ScriptRuntime.doTopCall: 3114
ANIunitTypes_27.call: 18
Context.lambda$call$0: 441
Context.$r8$lambda$U31uu1bHcE5ti_MlmtxLjUKGgyg: 0
Context$$ExternalSyntheticLambda0.run: 8
Context.call: 450
Context.call: 441
JavaAdapter.callMethod: 466
adapter22.setStats: 21
UnlockableContent.checkStats: 80
ContentInfoDialog.show: 30
DatabaseDialog.lambda$rebuild$4: 98
DatabaseDialog.$r8$lambda$LBTeAVmtLr0sVvCfpA_aJgyjSfA: 0
DatabaseDialog$$ExternalSyntheticLambda6.run: 2
Element.lambda$clicked$2: 893
Element.$r8$lambda$HTGgyzI_sft57MMc4a-IcKQNKts: 0
Element$$ExternalSyntheticLambda2.get: 4
Element$4.clicked: 902
ClickListener.touchUp: 77
InputListener.handle: 31
Scene.touchUp: 366
InputMultiplexer.touchUp: 136
AndroidInput.processEvents: 294
AndroidGraphics.onDrawFrame: 367
GLSurfaceView$GLThread.guardedRun: 1591
GLSurfaceView$GLThread.run: 1286

**Comment by FlinTyX** [comment]
So, I am trying to reproduce the error in my phone and It doesn't work, I don't know why. Looks like something breaks instantly in mobile devices. 

But as you have said, seems like the other frogs stats are working. I'm not sure if I can fix this.

```
Mods: animalia:0.1.2

NoSuchMethodError: 'No virtual method isDefault()Z in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-libart.jar)'
JavaAdapter.createAdapterCode: 301
JavaAdapter.getAdapterClass: 246
JavaAdapter.js_createAdapter: 160
JavaAdapter.execIdCall: 73
IdFunctionObject.call: 81
ScriptRuntime.applyOrCall: 2374
BaseFunction.execIdCall: 334
IdFunctionObject.call: 81
OptRuntime.call2: 32
global_js_1._c_extend_21: 41
global_js_1.call: -1
OptRuntime.callName: 51
ANIui_7._c_anonymous_1: 6
ANIui_7.call: -1
...
```

This should fix it, try installing it and tell me if it still crashes: [Animalia.zip](https://github.com/FlinTyX/Animalia/files/8414306/Animalia.zip)
